name: Build MySQL 5.7.33 ARM64 RPM

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      debug:
        description: '是否启用调试模式'
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache MySQL build
        uses: actions/cache@v3
        with:
          path: |
            /work/mysql
            ~/.ccache
          key: ${{ runner.os }}-mysql-5.7.33-${{ hashFiles('**/build-mysql-arm64.yml') }}
          restore-keys: |
            ${{ runner.os }}-mysql-5.7.33-
      
      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu20.04
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          dockerRunArgs: |
            --privileged
            --memory=16G
            --memory-swap=16G
            --cpus=2
            --env "MAKEFLAGS=-j1"
            --env "DEBIAN_FRONTEND=noninteractive"
            --env "TZ=Asia/Shanghai"
          install: |
            apt-get update && apt-get install -y sudo wget curl ca-certificates
          run: |
            # 设置非交互式环境变量，避免配置提示
            export DEBIAN_FRONTEND=noninteractive
            export TZ=Asia/Shanghai
            
          
            # 安装所有构建依赖
            sudo apt-get update
            sudo -E apt-get install -y \
              build-essential \
              cmake \
              git \
              rpm \
              alien \
              pkg-config \
              libncurses5-dev \
              libssl-dev \
              libaio-dev \
              libtirpc-dev \
              libwrap0-dev \
              libreadline-dev \
              zlib1g-dev \
              libpam0g-dev \
              libldap2-dev \
              libsasl2-dev \
              libnuma-dev \
              libjemalloc-dev \
              libevent-dev \
              libcurl4-openssl-dev \
              libxml2-dev \
              libffi-dev \
              libpcre3-dev \
              libedit-dev \
              libicu-dev \
              libboost-dev \
              libboost-system-dev \
              libboost-filesystem-dev \
              libboost-thread-dev \
              libboost-program-options-dev \
              libboost-iostreams-dev \
              libboost-regex-dev \
              libboost-date-time-dev \
              libboost-atomic-dev \
              libboost-chrono-dev \
              libboost-context-dev \
              libboost-coroutine-dev \
              linux-headers-generic \
              libevent-pthreads-2.1-7 \
              libevent-core-2.1-7 \
              libevent-extra-2.1-7 \
              libevent-openssl-2.1-7

            # 创建工作目录
            mkdir -p /work/mysql
            cd /work/mysql
            
            # 下载带 Boost 的 MySQL 5.7.33 源码
            wget https://dev.mysql.com/get/Downloads/MySQL-5.7/mysql-boost-5.7.33.tar.gz
            
            # MD5校验文件不可用，跳过验证
            echo "跳过MD5验证，直接继续构建..."
            
            # 解压源码
            tar xzf mysql-boost-5.7.33.tar.gz
            cd mysql-5.7.33
            
            # 创建编译目录
            mkdir build
            cd build 

            # 配置 MySQL 编译选项
            echo "开始配置 MySQL 编译选项..."
            cmake .. \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_C_FLAGS="-O0 -g0 -fno-omit-frame-pointer" \
              -DCMAKE_CXX_FLAGS="-O0 -g0 -fno-omit-frame-pointer" \
              -DCMAKE_INSTALL_PREFIX=/usr \
              -DMYSQL_DATADIR=/var/lib/mysql \
              -DSYSCONFDIR=/etc \
              -DINSTALL_INFODIR=share/mysql/docs \
              -DINSTALL_MANDIR=share/man \
              -DINSTALL_PLUGINDIR=lib/mysql/plugin \
              -DINSTALL_SCRIPTDIR=bin \
              -DINSTALL_INCLUDEDIR=include/mysql \
              -DINSTALL_DOCREADMEDIR=share/mysql \
              -DINSTALL_SUPPORTFILESDIR=share/mysql \
              -DINSTALL_MYSQLSHAREDIR=share/mysql \
              -DINSTALL_DOCDIR=share/mysql/docs \
              -DINSTALL_SHAREDIR=share/mysql \
              -DINSTALL_MYSQLTESTDIR=share/mysql/mysql-test \
              -DINSTALL_SQLBENCHDIR=share/mysql/sql-bench \
              -DINSTALL_MYSQLDATADIR=share/mysql/data \
              -DINSTALL_UNIX_ADDRDIR=/var/run/mysqld/mysqld.sock \
              -DWITH_SSL=system \
              -DWITH_ZLIB=system \
              -DWITH_LIBWRAP=ON \
              -DWITH_JEMALLOC=ON \
              -DWITH_EXTRA_CHARSETS=all \
              -DENABLED_LOCAL_INFILE=1 \
              -DWITH_EMBEDDED_SERVER=1 \
              -DWITH_INNODB_MEMCACHED=1 \
              -DWITH_ARCHIVE_STORAGE_ENGINE=1 \
              -DWITH_BLACKHOLE_STORAGE_ENGINE=1 \
              -DWITH_FEDERATED_STORAGE_ENGINE=1 \
              -DWITH_PARTITION_STORAGE_ENGINE=1 \
              -DWITH_PERFSCHEMA_STORAGE_ENGINE=1 \
              -DWITH_BOOST=../boost \
              -DWITH_SYSTEMD=0 \
              -DWITH_UNIT_TESTS=0 \
              -DWITHOUT_ROCKSDB=1 \
              -DWITHOUT_MROONGA=1 \
              -DWITHOUT_TOKUDB=1 \
              -DWITHOUT_CONNECT=1 \
              -DWITHOUT_NDBCLUSTER=1 \
              -DWITHOUT_NDB=1 \
              -DWITHOUT_NDBINFO=1 \
              -DWITHOUT_NDB_DEBUG=1 \
              -DWITHOUT_NDB_DEBUG_OPTS=1 \
              -DDISABLE_ABI_CHECK=1 || { echo "CMake 配置失败"; exit 1; }
            echo "MySQL 编译选项配置完成"

            # 编译 MySQL
            echo "开始编译 MySQL..."
            make -j1 VERBOSE=1 2>&1 | tee /work/mysql/build.log || { 
              echo "MySQL 编译失败，查看详细日志："
              cat /work/mysql/build.log
              echo "检查 mysys 目录的编译状态："
              ls -la mysys/CMakeFiles/mysys.dir/
              echo "检查系统内存状态："
              free -h
              echo "检查系统负载："
              top -b -n 1
              exit 1 
            }
            echo "MySQL 编译完成"
            
            # 安装到临时目录
            echo "开始安装 MySQL..."
            mkdir -p /tmp/mysql-install
            make install DESTDIR=/tmp/mysql-install || { echo "MySQL 安装失败"; exit 1; }
            echo "MySQL 安装完成"
            
            # 创建 .deb 包
            mkdir -p /tmp/mysql-deb/DEBIAN
            cat > /tmp/mysql-deb/DEBIAN/control << EOF
            Package: mysql
            Version: 5.7.33
            Section: database
            Priority: optional
            Architecture: arm64
            Maintainer: MySQL Builder <builder@example.com>
            Description: MySQL Database Server
            MySQL is a multi-user, multi-threaded SQL database server.
            EOF
            
            # 复制安装文件到包目录
            cp -r /tmp/mysql-install/* /tmp/mysql-deb/
            
            # 构建 .deb 包
            dpkg-deb --build /tmp/mysql-deb /work/mysql_5.7.33_arm64.deb
            
            # 使用 alien 将 .deb 包转换为 .rpm 包
            cd /work
            sudo alien --to-rpm --scripts mysql_5.7.33_arm64.deb
            
            # 列出生成的包
            ls -la /work/
            
            # 将 RPM 包复制到共享目录以便上传
            mkdir -p /github/workspace/output
            cp /work/*.rpm /github/workspace/output/
      
      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: mysql-5.7.33-arm64-rpm
          path: output/*.rpm
          retention-days: 30
            