name: Build MySQL 5.7.33 ARM64 RPM

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      debug:
        description: '是否启用调试模式'
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu20.04
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          dockerRunArgs: |
            --privileged
          install: |
            apt-get update && apt-get install -y sudo
          setup: |
            sudo apt-get update
            sudo apt-get install -y \
              build-essential \
              cmake \
              rpm \
              alien \
              wget \
              curl \
              git \
              libncurses5-dev \
              libssl-dev \
              libaio-dev \
              libtirpc-dev \
              libwrap0-dev \
              libreadline-dev \
              zlib1g-dev \
              libpam0g-dev \
              libldap2-dev \
              libsasl2-dev \
              libnuma-dev \
              libjemalloc-dev \
              libevent-dev \
              libcurl4-openssl-dev \
              libxml2-dev \
              libffi-dev \
              libpcre3-dev \
              libedit-dev \
              libicu-dev \
              libboost-dev \
              libboost-system-dev \
              libboost-filesystem-dev \
              libboost-thread-dev \
              libboost-program-options-dev \
              libboost-iostreams-dev \
              libboost-regex-dev \
              libboost-date-time-dev \
              libboost-atomic-dev \
              libboost-chrono-dev \
              libboost-context-dev \
              libboost-coroutine-dev
          run: |
            # 创建工作目录
            mkdir -p /work/mysql
            cd /work/mysql
            
            # 下载 MySQL 5.7.33 源码
            wget https://dev.mysql.com/get/Downloads/MySQL-5.7/mysql-5.7.33.tar.gz
            
            # 验证下载文件的完整性
            echo "正在验证下载文件的完整性..."
            wget https://dev.mysql.com/get/Downloads/MySQL-5.7/mysql-5.7.33.tar.gz.md5
            md5sum -c mysql-5.7.33.tar.gz.md5
            
            # 解压源码
            tar xzf mysql-5.7.33.tar.gz
            cd mysql-5.7.33
            
            # 创建编译目录
            mkdir build
            cd build 

            # 配置 MySQL 编译选项
            cmake .. \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_INSTALL_PREFIX=/usr \
              -DMYSQL_DATADIR=/var/lib/mysql \
              -DSYSCONFDIR=/etc \
              -DINSTALL_INFODIR=share/mysql/docs \
              -DINSTALL_MANDIR=share/man \
              -DINSTALL_PLUGINDIR=lib/mysql/plugin \
              -DINSTALL_SCRIPTDIR=bin \
              -DINSTALL_INCLUDEDIR=include/mysql \
              -DINSTALL_DOCREADMEDIR=share/mysql \
              -DINSTALL_SUPPORTFILESDIR=share/mysql \
              -DINSTALL_MYSQLSHAREDIR=share/mysql \
              -DINSTALL_DOCDIR=share/mysql/docs \
              -DINSTALL_SHAREDIR=share/mysql \
              -DINSTALL_MYSQLTESTDIR=share/mysql/mysql-test \
              -DINSTALL_SQLBENCHDIR=share/mysql/sql-bench \
              -DINSTALL_MYSQLDATADIR=share/mysql/data \
              -DINSTALL_UNIX_ADDRDIR=/var/run/mysqld/mysqld.sock \
              -DWITH_SSL=system \
              -DWITH_ZLIB=system \
              -DWITH_LIBWRAP=ON \
              -DWITH_JEMALLOC=ON \
              -DWITH_EXTRA_CHARSETS=all \
              -DENABLED_LOCAL_INFILE=1 \
              -DWITH_EMBEDDED_SERVER=1 \
              -DWITH_INNODB_MEMCACHED=1 \
              -DWITH_ARCHIVE_STORAGE_ENGINE=1 \
              -DWITH_BLACKHOLE_STORAGE_ENGINE=1 \
              -DWITH_FEDERATED_STORAGE_ENGINE=1 \
              -DWITH_PARTITION_STORAGE_ENGINE=1 \
              -DWITH_PERFSCHEMA_STORAGE_ENGINE=1 \
              -DWITH_BOOST=/usr \
              -DWITH_SYSTEMD=0 \
              -DWITH_UNIT_TESTS=0 \
              -DWITHOUT_ROCKSDB=1 \
              -DWITHOUT_MROONGA=1 \
              -DWITHOUT_TOKUDB=1 \
              -DWITHOUT_CONNECT=1 \
              -DWITHOUT_NDBCLUSTER=1 \
              -DWITHOUT_NDB=1 \
              -DWITHOUT_NDBINFO=1 \
              -DWITHOUT_NDB_DEBUG=1 \
              -DWITHOUT_NDB_DEBUG_OPTS=1

            # 编译 MySQL
            make -j$(nproc)
            
            # 安装到临时目录
            mkdir -p /tmp/mysql-install
            make install DESTDIR=/tmp/mysql-install
            
            # 创建 .deb 包
            mkdir -p /tmp/mysql-deb/DEBIAN
            cat > /tmp/mysql-deb/DEBIAN/control << EOF
            Package: mysql
            Version: 5.7.33
            Section: database
            Priority: optional
            Architecture: arm64
            Maintainer: MySQL Builder <builder@example.com>
            Description: MySQL Database Server
             MySQL is a multi-user, multi-threaded SQL database server.
            EOF
            
            # 复制安装文件到包目录
            cp -r /tmp/mysql-install/* /tmp/mysql-deb/
            
            # 构建 .deb 包
            dpkg-deb --build /tmp/mysql-deb /work/mysql_5.7.33_arm64.deb
            
            # 使用 alien 将 .deb 包转换为 .rpm 包
            cd /work
            sudo alien --to-rpm --scripts mysql_5.7.33_arm64.deb
            
            # 列出生成的包
            ls -la /work/
            
            # 将 RPM 包复制到共享目录以便上传
            mkdir -p /github/workspace/output
            cp /work/*.rpm /github/workspace/output/
      
      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: mysql-5.7.33-arm64-rpm
          path: output/*.rpm
          retention-days: 30
            